### PR TITLE
Resource page added

### PR DESCRIPTION
**Pull request by Sabique-Islam**
Created resource page with responsive UI and hover effects.

### CODE REVIEW

**Comment by Sabique-Islam** [comment]
added the styles

**Comment by reema-s1** [comment]
!bounty 100

**Comment by reema-s1** [comment]
!bounty 185

**Comment by Sabique-Islam** [comment]
@reema-s1 was the 185 bounty specifically for products page? If yes, then my total bounty points must be 285 ( + 100 for the earlier documentation page).

**Comment by bwaklog** [comment]
Hi @Sabique-Islam I'm part of the tech team of the event!

So when we issue 2 _different_ bounties in a PR, that means the latest PR is considered to be the points assigned. Hence we don’t add up each of the bounties. 

> [Assigned 100 Bounty points to user @Sabique-Islam !](https://github.com/acmpesuecc/flowforge/pull/8#issuecomment-2423326174)

> [Assigned 185 Bounty points to user @Sabique-Islam !](https://github.com/acmpesuecc/flowforge/pull/8#issuecomment-2423472705)

Hence, the maintainer has decided to allot 185 issues for this PR, and not 100 + 185

**Pull request closed without merging**
